import * as core from "@actions/core";
import * as exec from "@actions/exec";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

/**
 * SSH Authentication Module
 * Handles SSH key setup, validation, and git configuration for SSH-based authentication
 */

/**
 * Read SSH-related inputs from GitHub Actions
 * @returns {Object} SSH configuration
 */
export function readSSHInputs() {
  return {
    sshKey: core.getInput("ssh_key"),
    sshKeyPath: core.getInput("ssh_key_path"),
    sshPassphrase: core.getInput("ssh_passphrase"),
    sshKnownHostsPath: core.getInput("ssh_known_hosts_path"),
    sshStrictHostKeyChecking: core.getInput("ssh_strict_host_key_checking") !== "false", // Default true
  };
}

/**
 * Detect if a URL is SSH-based
 * @param {string} url - Repository URL
 * @returns {boolean} True if URL uses SSH protocol
 */
export function isSSHUrl(url) {
  // SSH URLs start with git@, ssh://, or use ssh protocol
  return url.startsWith("git@") || url.startsWith("ssh://");
}

/**
 * Detect which repositories use SSH
 * @param {string} sourceRepo - Source repository URL
 * @param {string} destinationRepo - Destination repository URL
 * @returns {Object} SSH configuration for each repo
 */
export function detectAuthenticationMethods(sourceRepo, destinationRepo) {
  const sourceIsSSH = isSSHUrl(sourceRepo);
  const destinationIsSSH = isSSHUrl(destinationRepo);

  core.debug(`Source repo SSH: ${sourceIsSSH} (${sourceRepo})`);
  core.debug(`Destination repo SSH: ${destinationIsSSH} (${destinationRepo})`);

  return {
    sourceIsSSH,
    destinationIsSSH,
    needsSSH: sourceIsSSH || destinationIsSSH,
  };
}

/**
 * Create SSH directory with proper permissions
 * @returns {string} Path to SSH directory
 */
export function setupSSHDirectory() {
  const sshDir = path.join(os.homedir(), ".ssh");

  if (!fs.existsSync(sshDir)) {
    core.info("Creating .ssh directory...");
    fs.mkdirSync(sshDir, { mode: 0o700 });
    core.info("✓ .ssh directory created");
  } else {
    core.debug(".ssh directory already exists");
  }

  // Ensure correct permissions
  fs.chmodSync(sshDir, 0o700);

  return sshDir;
}

/**
 * Write SSH key to file with proper permissions
 * @param {string} sshKeyContent - SSH private key content
 * @param {string} sshDir - SSH directory path
 * @param {string} keyName - Name of the key file (default: id_rsa)
 * @returns {string} Path to the key file
 */
export function writeSSHKey(sshKeyContent, sshDir, keyName = "id_rsa") {
  if (!sshKeyContent) {
    throw new Error("SSH key content is required");
  }

  const keyPath = path.join(sshDir, keyName);

  core.info(`Writing SSH key to ${keyName}...`);

  // Handle keys with escaped newlines or base64 encoded
  let keyContent = sshKeyContent;

  // If key contains escaped newlines (\\n), replace with actual newlines
  if (keyContent.includes("\\n")) {
    keyContent = keyContent.replace(/\\n/g, "\n");
  }

  // If key is base64 encoded (no BEGIN/END markers), decode it
  if (!keyContent.includes("BEGIN") && !keyContent.includes("END")) {
    try {
      keyContent = Buffer.from(keyContent, "base64").toString("utf-8");
      core.debug("SSH key was base64 encoded, decoded successfully");
    } catch (error) {
      core.warning("Could not decode SSH key as base64, using as-is");
    }
  }

  // Ensure key ends with newline
  if (!keyContent.endsWith("\n")) {
    keyContent += "\n";
  }

  // Write key to file
  fs.writeFileSync(keyPath, keyContent, { mode: 0o600 });
  core.info(`✓ SSH key written to ${keyName}`);

  return keyPath;
}

/**
 * Setup SSH config for hosts
 * @param {string} sshDir - SSH directory path
 */
export function setupSSHConfig(sshDir) {
  const configPath = path.join(sshDir, "config");

  // SSH config for common hosts to improve performance and security
  const sshConfig = `# Auto-generated by github-sync action
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking accept-new

Host gitlab.com
  HostName gitlab.com
  User git
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking accept-new

Host gitea.*
  User git
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking accept-new

Host gerrit.*
  User git
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking accept-new

# Fallback for other hosts
Host *
  User git
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking accept-new
  AddKeysToAgent yes
`;

  if (!fs.existsSync(configPath)) {
    core.info("Creating SSH config...");
    fs.writeFileSync(configPath, sshConfig, { mode: 0o600 });
    core.info("✓ SSH config created");
  } else {
    core.debug("SSH config already exists");
  }
}

/**
 * Setup known hosts to avoid SSH prompts
 * @param {string} sshDir - SSH directory path
 * @param {string} customKnownHostsPath - Optional custom known_hosts file path
 */
export async function setupKnownHosts(sshDir, customKnownHostsPath) {
  const knownHostsPath = customKnownHostsPath || path.join(sshDir, "known_hosts");

  core.info("Setting up known_hosts...");

  // Common host keys
  const knownHosts = [
    'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndgoebf+alrspvfHZEfEIiu1cOyT16CPrMdLvzexPn0DblIWXKc8NyVN++5c2lNB6+7aMg6i6RQaKL8IrKGcorfzi7EC4Jq9Nkz0f+5dn0AHqTJl1lUqhVl3xGrT+rwG88qtqqIvzlWPPC2bRDe7XSGIYvHbFqwCRuPvz0XZ2xZ5g+v96SxQ8wtLn0=',
    'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl',
    'github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQwcKllNydjgE8Z7mRFot2+kT7nWrniA9n+vj/weIonvg7E2nw8XByT31PdhznVA8phxWtNGgd+hF5Q4=',
    'gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKZm5AD5E1F2d5As+BltSrZRQJJZchreQvAxZSDA7HBFcqLHWXwpxhlnkqKaE5/+FvAZ3GNPiMaUL5yO7VD20A7yVjaSMzQyMA1+X9rpyWTRpnrHARkYvIygH8dHbXGIvQvIWnM7TCyNuTpVndHIlySRIJWMChBotauKpmZ5TZHhc5+5W/cCrc8DKw8SnAc8bUZAJXwKoExD7+Fe7zNx7UnLAEIjI+3l5+FfeKvIZ5F4Nm5+5p00a7tagvBXWwzrniA9n2Bp4w8v+VreLAQRK/E4xuchhughes28y7ElW9/4ub3ISTmRCv43LilBtvSoGWT8=',
    'gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGV3/pHk5/IIJXci6ex23I9Q3irrKH+IlaWQSo/BBoD+',
  ];

  try {
    if (fs.existsSync(knownHostsPath)) {
      core.debug("known_hosts already exists");
    } else {
      core.info("Creating known_hosts file...");
      fs.writeFileSync(knownHostsPath, knownHosts.join("\n") + "\n", {
        mode: 0o600,
      });
      core.info("✓ known_hosts file created");
    }
  } catch (error) {
    core.warning(`Could not setup known_hosts: ${error.message}`);
  }
}

/**
 * Start SSH agent and load keys
 * @param {string} keyPath - Path to SSH key file
 * @param {string} passphrase - Optional passphrase for encrypted keys
 */
export async function startSSHAgent(keyPath, passphrase) {
  core.info("=== Setting up SSH Agent ===");

  try {
    // Check if SSH agent is already running
    const agentSockEnv = process.env.SSH_AUTH_SOCK;
    if (agentSockEnv) {
      core.info("SSH agent already running");
    } else {
      core.info("Starting SSH agent...");
      const output = await exec.getExecOutput("ssh-agent", ["-s"]);
      // Parse and set environment variables from ssh-agent output
      const lines = output.stdout.split("\n");
      for (const line of lines) {
        if (line.includes("SSH_AUTH_SOCK")) {
          const match = line.match(/SSH_AUTH_SOCK=([^;]+)/);
          if (match) {
            process.env.SSH_AUTH_SOCK = match[1];
          }
        } else if (line.includes("SSH_AGENT_PID")) {
          const match = line.match(/SSH_AGENT_PID=([^;]+)/);
          if (match) {
            process.env.SSH_AGENT_PID = match[1];
          }
        }
      }
      core.info("✓ SSH agent started");
    }

    // Add key to agent
    core.info("Adding SSH key to agent...");
    if (passphrase) {
      // Use ssh-add with passphrase (via stdin)
      await exec.exec("ssh-add", [keyPath], {
        input: Buffer.from(passphrase + "\n"),
        silent: true,
      });
    } else {
      // Add key without passphrase
      await exec.exec("ssh-add", [keyPath]);
    }
    core.info("✓ SSH key added to agent");
  } catch (error) {
    core.error(`SSH agent setup failed: ${error.message}`);
    throw error;
  }
}

/**
 * Validate SSH setup and connectivity
 * @param {string} host - Host to test (default: github.com)
 */
export async function validateSSHSetup(host = "github.com") {
  core.info("=== Validating SSH Setup ===");

  try {
    // Test SSH connection
    core.info(`Testing SSH connection to ${host}...`);
    const output = await exec.getExecOutput("ssh", ["-v", "-T", `git@${host}`], {
      ignoreReturnCode: true,
    });

    // SSH to git server typically returns exit code 1 but with successful auth
    // We're looking for "successfully authenticated" in output
    if (
      output.stdout.includes("successfully authenticated") ||
      output.stderr.includes("successfully authenticated") ||
      output.stderr.includes("authenticated")
    ) {
      core.info(`✓ SSH authentication successful for ${host}`);
      return true;
    } else if (output.stdout.includes("Permission denied") || output.stderr.includes("Permission denied")) {
      core.error(`SSH authentication failed for ${host}: Permission denied`);
      return false;
    } else {
      core.debug(`SSH test output: ${output.stdout}`);
      core.debug(`SSH test stderr: ${output.stderr}`);
      // Some servers might not support -T flag, but connection might still work
      core.warning(`Could not fully validate SSH setup, proceeding with caution`);
      return true;
    }
  } catch (error) {
    core.error(`SSH validation failed: ${error.message}`);
    throw error;
  }
}

/**
 * Full SSH setup orchestration
 * @param {Object} sshConfig - SSH configuration object
 * @param {string} sshConfig.sshKey - SSH private key content
 * @param {string} sshConfig.sshKeyPath - Alternative SSH key file path
 * @param {string} sshConfig.sshPassphrase - Passphrase for encrypted keys
 * @param {string} sshConfig.sshKnownHostsPath - Custom known_hosts path
 * @param {boolean} sshConfig.sshStrictHostKeyChecking - Enable strict host key checking
 */
export async function setupSSHAuthentication(sshConfig) {
  // If no SSH key provided, assume SSH is already configured on runner
  if (!sshConfig.sshKey && !sshConfig.sshKeyPath) {
    core.info("No SSH key provided, assuming SSH is already configured");
    return;
  }

  core.info("=== SSH Authentication Setup ===");

  try {
    // Setup SSH directory
    const sshDir = setupSSHDirectory();

    // Write SSH key to file
    let keyPath;
    if (sshConfig.sshKey) {
      keyPath = writeSSHKey(sshConfig.sshKey, sshDir);
    } else if (sshConfig.sshKeyPath) {
      if (!fs.existsSync(sshConfig.sshKeyPath)) {
        throw new Error(`SSH key file not found: ${sshConfig.sshKeyPath}`);
      }
      keyPath = sshConfig.sshKeyPath;
      core.info(`Using SSH key from: ${keyPath}`);
    }

    // Setup SSH config
    setupSSHConfig(sshDir);

    // Setup known_hosts
    await setupKnownHosts(sshDir, sshConfig.sshKnownHostsPath);

    // Start SSH agent and load key
    await startSSHAgent(keyPath, sshConfig.sshPassphrase);

    // Validate SSH setup
    await validateSSHSetup("github.com");

    core.info("✓ SSH authentication setup completed successfully");
  } catch (error) {
    core.error(`SSH setup failed: ${error.message}`);
    throw error;
  }
}
